### PR TITLE
Saving prediction as jpeg, sample video output and uniform usage of opencv

### PR DESCRIPTION
**Pull request by Sharanranjit**

### CODE REVIEW

**Comment by ashwinvaswani** [comment]
Hey. It looks okay but I'd mentioned having a save_figure flag set to false by default and only saving predictions when explicitly required by user. Kindly check the comments on that issue that I updated recently and update your PR. Best of luck!

**Comment by ashwinvaswani** [comment]
Rest seems okay

**Comment by Sharanranjit** [comment]
Yep, its done now. Also, I think the FPS issue is solved now that we are writing back the output frames, you can view the sample_video_output i have committed.

**Comment by ashwinvaswani** [comment]
Yes but by FPS issue, I meant while rendering( total processing time of video) before output video is ready

**Pull request merged**
